### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by okonet** [raulanatol/axios-etag-cache#3]
I'm trying to integrate it with https://github.com/jongold/figma-js like this:

```diff
- const client = axios.create({
+ const client = axiosETAGCache({
    baseURL: `https://${opts.apiRoot || 'api.figma.com'}/v1/`,
    headers
  });
```

but then I'm getting this as soon as I invoke any of `get` methods on the client

```
TypeError: Cannot read property 'status' of undefined
    at f (/Users/okonet/Projects/OSS/figma-js/node_modules/axios-etag-cache/dist/index.js:1:11673)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:800:11)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
```

Ideas?

**Comment by raulanatol** [comment]
Hi @okonet 
Could be related to your API response.
We only use *.status after an API error like this:
```
error.response.status
```
Could you check if the error object has a response field in your API?
